version: "2"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "~/postgres-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=imperialeagle"
    container_name: "overcomplicated-database"
