version: "2"
services:
  api:
    build:
      context: "."
      dockerfile: "./api/Dockerfile"
    ports:
      - "3000:3000"
    environment:
      - "NODE_ENV=production"
    links:
      - "postgres:postgres"
  auth:
    build:
      context: "."
      dockerfile: "./auth/Dockerfile"
    ports:
      - "8000:8000"
    environment:
      - "NODE_ENV=production"
    links:
      - "postgres:postgres"
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
      - "~/postgres-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=imperialeagle"
    container_name: "overcomplicated-database"
